import { StyleSheet } from "react-native";
import Colors from "./Colors";
import i18n from "i18n-js";

export const SIZES = {
  BASE: 6,
  FONT: 12,
  FONT2: 16,
  FONT3: 20,
  TITLE: 48,
  PADDING: 12,
};

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: SIZES.BASE * 4,
    backgroundColor: Colors.WHITE,
  },
  input: {
    padding: 10,
    paddingTop: 15,
    paddingBottom: 15,
    color: Colors.BLACK,
    fontSize: SIZES.FONT2,
    fontFamily: i18n.t("regular"),
    // backgroundColor:"red",
    flex: 1,
    // paddingVertical: SIZES.PADDING * 0.5,
  },
  inputContainer: {
    marginBottom: SIZES.PADDING * 2,
    flexDirection: "row",
    height: 50,
    backgroundColor: Colors.BGray,
    borderColor: Colors.BLACK,
    // borderWidth: StyleSheet.hairlineWidth,
    alignItems: "center",
    paddingLeft: 15,
    borderRadius: 25,

    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,

    elevation: 1,
  },

  search: {
    padding: 20,
    paddingTop: 15,
    paddingBottom: 15,
    color: Colors.BLACK,
    fontSize: SIZES.FONT2,
    fontFamily: i18n.t("regular"),
    // backgroundColor:"red",
    flex: 1,
    // paddingVertical: SIZES.PADDING * 0.5,
  },
  searchContainer: {
    marginBottom: SIZES.PADDING * 2,
    flexDirection: "row",
    height: 50,
    backgroundColor: Colors.WHITE,
    borderColor: Colors.DGray,
    borderWidth: 0.17,
    alignItems: "center",
    marginLeft:20,
    marginRight:20,
    paddingLeft: 20,
    borderRadius: 25,
    marginTop:20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,

    elevation: 1,
  },
  signin: {
    backgroundColor: Colors.BLACK,
    borderRadius: SIZES.BASE * 5,
    paddingVertical: SIZES.PADDING,
    height: 50,
    justifyContent: "center",
    textAlign: "center",

    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,

    elevation: 1,
  },
  signinLabel: {
    color: Colors.WHITE,
    fontSize: SIZES.FONT2,
    // fontWeight: "600",
    fontFamily: i18n.t("black"),
    letterSpacing: 0.5,
    textAlign: "center",
  },
  title: {
    color: Colors.DYellow,
    fontSize: SIZES.TITLE,
    // fontWeight: "700",
    fontFamily: i18n.t("bold"),
    letterSpacing: 1,
    marginBottom: SIZES.BASE,
  },
  title2: {
    color: Colors.BLACK,
    fontSize: SIZES.FONT2,
    fontFamily: i18n.t("regular"),
    // fontWeight: "400",
    letterSpacing: 1,
    marginBottom: SIZES.BASE,
  },

  viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	nounMenu1812743Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 25,
		height: 18,
		marginTop: 7,
	},
	nounShoppingCart1Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		position: "absolute",
		right: 6,
		width: 25,
		top: 1,
		height: 27,
	},
	ellipse234View: {
		backgroundColor: "rgb(234, 169, 73)",
		borderRadius: 7.5,
		position: "absolute",
		right: 0,
		width: 15,
		top: 0,
		height: 15,
	},
	textText: {
		color: "white",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 9,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		right: 4,
		top: 2,
	},
	rectangle97View: {
		backgroundColor: "white",
		borderRadius: 24,
		borderWidth: 1,
		borderColor: "rgb(230, 230, 230)",
		borderStyle: "solid",
		shadowColor: "rgba(0, 0, 0, 0.15)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 48,
	},
	nounSearch1868247Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 22,
		height: 21,
	},
	startSearchingForText: {
		backgroundColor: "transparent",
		opacity: 0.51,
		color: "rgb(49, 49, 49)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 18,
		marginTop: 4,
	},
	campaign02Ban01Image: {
		backgroundColor: "transparent",
		resizeMode: "cover",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 184,
	},
	wowDealsText: {
		backgroundColor: "transparent",
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 48,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 48,
		paddingTop: 14,
		position: "absolute",
		left: 20,
		top: 36,
	},
	shopByCategoryText: {
		backgroundColor: "transparent",
		color: "rgb(234, 169, 73)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	seeAllText: {
		backgroundColor: "transparent",
		color: "rgb(17, 17, 17)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	youngManWomanSittImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		width: 147,
		top: 0,
		height: 176,
	},
	shopFashionText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Poppins-Bold",
		fontSize: 21,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "left",
		lineHeight: 24,
		paddingTop: 6,
		position: "absolute",
		left: 18,
		top: 103,
	},
	brightYellowAccessImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 90,
		height: 84,
	},
	horizontalFancyMulImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 90,
		height: 84,
		marginTop: 8,
	},
	twoElegantGlamorHImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 90,
		height: 84,
	},
	setLuxuryPerfumeBImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 90,
		height: 84,
		marginTop: 8,
	},
	forHerText: {
		backgroundColor: "transparent",
		color: "rgb(234, 169, 73)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	shopNowText: {
		backgroundColor: "transparent",
		color: "rgb(17, 17, 17)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	rectangle118View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 150,
		top: 0,
		height: 89,
	},
	shortDressForWomeText: {
		backgroundColor: "transparent",
		color: "rgb(20, 20, 20)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 20,
	},
	group493Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 24,
		height: 18,
		marginTop: 1,
	},
	nounHeart3104971Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.41,
		width: 20,
		height: 17,
		marginLeft: 10,
		marginTop: 2,
	},
	group492View: {
		backgroundColor: "transparent",
		width: 16,
		height: 17,
		marginLeft: 11,
	},
	group481Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		flex: 1,
		height: 6,
		marginRight: 3,
	},
	group487View: {
		backgroundColor: "transparent",
		flex: 1,
		height: 17,
		marginLeft: 3,
	},
	group483Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 6,
		marginRight: 1,
	},
	group485Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 6,
		marginLeft: 1,
	},
	group488Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 5,
	},
	group490Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 5,
		marginTop: 1,
	},
	rectangle119View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 150,
		top: 0,
		height: 89,
	},
	shortDressForWomeTwoText: {
		backgroundColor: "transparent",
		color: "rgb(20, 20, 20)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 20,
	},
	group493TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 24,
		height: 18,
		marginRight: 10,
		marginTop: 1,
	},
	nounHeart3104971TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.41,
		width: 20,
		height: 17,
		marginRight: 11,
		marginTop: 2,
	},
	group492TwoView: {
		backgroundColor: "transparent",
		width: 16,
		height: 17,
	},
	group481TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		flex: 1,
		height: 6,
		marginRight: 3,
	},
	group487TwoView: {
		backgroundColor: "transparent",
		flex: 1,
		height: 17,
		marginLeft: 3,
	},
	group483TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 6,
		marginRight: 1,
	},
	group485TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 6,
		marginLeft: 1,
	},
	group488TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 5,
	},
	group490TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 5,
		marginTop: 1,
	},
	rectangle120View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 150,
		top: 0,
		height: 89,
	},
	shortDressForWomeThreeText: {
		backgroundColor: "transparent",
		color: "rgb(20, 20, 20)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 20,
	},
	group493ThreeImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 24,
		height: 18,
		marginRight: 87,
		marginTop: 11,
	},
	forHimText: {
		color: "rgb(234, 169, 73)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	shopNowTwoText: {
		color: "rgb(17, 17, 17)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	portraitElegantBruImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		width: 150,
		top: 0,
		height: 205,
	},
	rectangle121View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 150,
		top: 116,
		height: 89,
	},
	blueShirtForMen2Text: {
		color: "rgb(20, 20, 20)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 20,
		backgroundColor: "transparent",
	},
	group493FourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 24,
		height: 18,
		marginTop: 1,
	},
	nounHeart3104971ThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.41,
		width: 20,
		height: 17,
		marginLeft: 10,
		marginTop: 2,
	},
	group492ThreeView: {
		backgroundColor: "transparent",
		width: 16,
		height: 17,
		marginLeft: 11,
	},
	group481ThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		flex: 1,
		height: 6,
		marginRight: 3,
	},
	group487ThreeView: {
		backgroundColor: "transparent",
		flex: 1,
		height: 17,
		marginLeft: 3,
	},
	group483ThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 6,
		marginRight: 1,
	},
	group485ThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 6,
		marginLeft: 1,
	},
	group488ThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 5,
	},
	group490ThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 5,
		marginTop: 1,
	},
	handsomeElegantManImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		right: 0,
		width: 150,
		top: 0,
		height: 205,
	},
	rectangle122View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 150,
		top: 116,
		height: 89,
	},
	blueShirtForMen2TwoText: {
		backgroundColor: "transparent",
		color: "rgb(20, 20, 20)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 20,
	},
	group493FiveImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 24,
		height: 18,
		marginRight: 10,
		marginTop: 1,
	},
	nounHeart3104971FourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.41,
		width: 20,
		height: 17,
		marginRight: 11,
		marginTop: 2,
	},
	group492FourView: {
		backgroundColor: "transparent",
		width: 16,
		height: 17,
	},
	group481FourImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		flex: 1,
		height: 6,
		marginRight: 3,
	},
	group487FourView: {
		backgroundColor: "transparent",
		flex: 1,
		height: 17,
		marginLeft: 3,
	},
	group483FourImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 6,
		marginRight: 1,
	},
	group485FourImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 6,
		marginLeft: 1,
	},
	group488FourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 5,
	},
	group490FourImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 5,
		marginTop: 1,
	},
	manFastensCuffsHiImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		right: 0,
		width: 150,
		top: 0,
		height: 205,
	},
	rectangle123View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 150,
		top: 116,
		height: 89,
	},
	blueShirtForMen2ThreeText: {
		color: "rgb(20, 20, 20)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 20,
		backgroundColor: "transparent",
	},
	group493SixImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 24,
		height: 18,
		marginRight: 60,
		marginTop: 11,
	},
	youJustViewedText: {
		color: "rgb(234, 169, 73)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		marginLeft: 13,
		marginBottom: 23,
	},
	prettyBlondeInlongTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		width: 150,
		bottom: 0,
		height: 205,
	},
	rectangle124View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 150,
		bottom: 0,
		height: 89,
	},
	shortDressForWomeFourText: {
		color: "rgb(20, 20, 20)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 20,
		backgroundColor: "transparent",
		marginBottom: 10,
	},
	group493SevenImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 24,
		height: 18,
	},
	nounHeart3104971FiveImage: {
		backgroundColor: "transparent",
		opacity: 0.41,
		resizeMode: "center",
		width: 20,
		height: 17,
		marginLeft: 10,
	},
	group492FiveView: {
		backgroundColor: "transparent",
		width: 16,
		height: 17,
		marginLeft: 11,
		marginBottom: 2,
	},
	group481FiveImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		flex: 1,
		height: 6,
		marginRight: 3,
	},
	group487FiveView: {
		backgroundColor: "transparent",
		flex: 1,
		height: 17,
		marginLeft: 3,
	},
	group483FiveImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 6,
		marginRight: 1,
	},
	group485FiveImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 6,
		marginLeft: 1,
	},
	group488FiveImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 5,
	},
	group490FiveImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 5,
		marginTop: 1,
	},
	cuteTeenageGirlFaTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		right: 0,
		width: 150,
		bottom: 0,
		height: 205,
	},
	rectangle125View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 150,
		bottom: 0,
		height: 89,
	},
	shortDressForWomeFiveText: {
		backgroundColor: "transparent",
		color: "rgb(20, 20, 20)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 20,
		marginBottom: 10,
	},
	group493EightImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 24,
		height: 18,
		marginRight: 10,
	},
	nounHeart3104971SixImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.41,
		width: 20,
		height: 17,
		marginRight: 11,
	},
	group492SixView: {
		backgroundColor: "transparent",
		width: 16,
		height: 17,
		marginBottom: 2,
	},
	group481SixImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		flex: 1,
		height: 6,
		marginRight: 3,
	},
	group487SixView: {
		backgroundColor: "transparent",
		flex: 1,
		height: 17,
		marginLeft: 3,
	},
	group483SixImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 6,
		marginRight: 1,
	},
	group485SixImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 6,
		marginLeft: 1,
	},
	group488SixImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 5,
	},
	group490SixImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 5,
		marginTop: 1,
	},
	womanClothingAccesTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		right: 0,
		width: 150,
		bottom: 0,
		height: 205,
	},
	rectangle126View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 150,
		bottom: 0,
		height: 89,
	},
	shortDressForWomeSixText: {
		backgroundColor: "transparent",
		color: "rgb(20, 20, 20)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 20,
		marginBottom: 11,
	},
	group493NineImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 24,
		height: 18,
		marginRight: 87,
	},
	rectangle113View: {
		backgroundColor: "rgb(239, 239, 239)",
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 105,
	},
	group480Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 29,
		height: 28,
		marginBottom: 15,
	},
	homeText: {
		backgroundColor: "transparent",
		color: "rgb(171, 171, 171)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 9,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 1,
	},
	nounCategory283436Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 27,
		height: 27,
		marginBottom: 14,
	},
	shopsText: {
		color: "rgb(171, 171, 171)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 9,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	group477Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 16,
		height: 27,
		marginRight: 47,
		marginBottom: 28,
	},
	nounCart1363648Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 30,
		height: 28,
		marginRight: 5,
		marginBottom: 15,
	},
	myCartText: {
		color: "rgb(171, 171, 171)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 9,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	group479Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 23,
		height: 28,
		marginBottom: 14,
	},
	meText: {
		color: "rgb(171, 171, 171)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 9,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginRight: 4,
	},
	group1702View: {
		backgroundColor: "transparent",
		width: 56,
		height: 62,
	},
	group1701Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 35,
		marginLeft: 8,
		marginRight: 8,
	},
	brandShopText: {
		backgroundColor: "transparent",
		color: "rgb(45, 45, 45)",
		fontSize: 8,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "right",
		marginBottom: 3,
	},
	shoppingMadnessText: {
		backgroundColor: "transparent",
		color: "rgb(45, 45, 45)",
		fontSize: 4,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "right",
		marginLeft: 9,
		marginRight: 7,
	},
	prettyBlondeInlongImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 150,
		height: 205,
	},
	cuteTeenageGirlFaImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 150,
		height: 205,
		marginRight: 9,
	},
	womanClothingAccesImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 150,
		height: 205,
	},
	dealsText: {
		backgroundColor: "transparent",
		color: "rgb(234, 169, 73)",
		fontFamily: "Poppins-ExtraLight",
		fontSize: 9,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
  
});
